language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - mkdir -p deploy
  - cp src/main/resources/application.yml before-deploy
  - cp deploy.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy/ && zip -r before-deploy *
  - cd ..
  - mv before-deploy/before-deploy.zip deploy/monitor-assistant.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cscapstone-21-1-5-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: cscapstone-21-1-5-s3
    key: monitor-assistant.zip
    bundle_type: zip
    application: BEDeployment
    deployment_group: BEDeployGroup
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - jwurbane97@ajou.ac.kr
      - ju2173@ajou.ac.kr
      - hehesi2007@ajou.ac.kr
      - ghdwn0120@ajou.ac.kr

