spring:
  devtools:
    livereload:
      enabled: true
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /api
    display-request-duration: true
    groups-order: DESC
jwt:
  secret: monitorAssistant